name: "Build and Push Docker Compose images."
description: "Build and Push Docker images to a registry using a docker compose specification"
author: mattvogel

inputs:
  context:
    description: "The build context for the Docker images"
    required: true
    default: "."
  compose-file:
    description: "The Dockerfile to use for building the images"
    required: true
    default: "Dockerfile"
  push:
    description: "Whether to push the images to the registry"
    required: true
    default: "true"
  tag:
    description: "The tags to apply to the images"
    required: true
    default: "latest"
  registry:
    description: "The registry to push the images to"
    required: true
    default: "docker.pkg.github.com"
  username:
    description: "The username to use for the registry"
    required: false
  password:
    description: "The password to use for the registry"
    required: false
  

outputs:
  imageids:
    description: "The image ids of the images that were built"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    COMPOSE_CONTEXT: ${{ inputs.context }}
    COMPOSE_FILE: ${{ inputs.compose-file }}
    COMPOSE_PUSH: ${{ inputs.push }}
    COMPOSE_TAGS: ${{ inputs.tag }}
    COMPOSE_REGISTRY: ${{ inputs.registry }}
    COMPOSE_USERNAME: ${{ inputs.username }}
    COMPOSE_PASSWORD: ${{ inputs.password }}
    
