name: test
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        uses: mattvogel/build-push-docker-compose@v0.0.4
        with:
          context: .
          compose-file: docker-compose.yml
          registry: ${{ steps.login-ecr.outputs.registry }}
          username: ${{ steps.login-ecr.outputs.docker_username }}
          password: ${{ steps.login-ecr.outputs.docker_password }}
          tags: ${{ github.sha }}